<?php

namespace Database\Seeders;

use App\Models\Parroquia;
use App\Models\City;
use Illuminate\Database\Seeder;

class ParishesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $parishes = [
            ['id' => '1','name' => 'Fernando Girón Tovar','city_id' => '47263','created_at' => NULL,'updated_at' => NULL],
            ['id' => '2','name' => 'Luis Alberto Gómez','city_id' => '47263','created_at' => NULL,'updated_at' => NULL],
            ['id' => '3','name' => 'Parhueña','city_id' => '47263','created_at' => NULL,'updated_at' => NULL],
            ['id' => '4','name' => 'Platanillal','city_id' => '47263','created_at' => NULL,'updated_at' => NULL],
            ['id' => '5','name' => 'Anaco','city_id' => '47264','created_at' => NULL,'updated_at' => NULL],
            ['id' => '6','name' => 'San Joaquín','city_id' => '47264','created_at' => NULL,'updated_at' => NULL],
            ['id' => '7','name' => 'Barcelona','city_id' => '47265','created_at' => NULL,'updated_at' => NULL],
            ['id' => '8','name' => 'El Carmen','city_id' => '47265','created_at' => NULL,'updated_at' => NULL],
            ['id' => '9','name' => 'San Cristóbal','city_id' => '47265','created_at' => NULL,'updated_at' => NULL],
            ['id' => '10','name' => 'Bergantín','city_id' => '47265','created_at' => NULL,'updated_at' => NULL],
            ['id' => '11','name' => 'Caigua','city_id' => '47265','created_at' => NULL,'updated_at' => NULL],
            ['id' => '12','name' => 'El Pilar','city_id' => '47265','created_at' => NULL,'updated_at' => NULL],
            ['id' => '13','name' => 'Naricual','city_id' => '47265','created_at' => NULL,'updated_at' => NULL],
            ['id' => '14','name' => 'San José','city_id' => '47265','created_at' => NULL,'updated_at' => NULL],
            ['id' => '15','name' => 'Cantaura','city_id' => '47266','created_at' => NULL,'updated_at' => NULL],
            ['id' => '16','name' => 'Libertador','city_id' => '47266','created_at' => NULL,'updated_at' => NULL],
            ['id' => '17','name' => 'Santa Rosa','city_id' => '47266','created_at' => NULL,'updated_at' => NULL],
            ['id' => '18','name' => 'Urica','city_id' => '47266','created_at' => NULL,'updated_at' => NULL],
            ['id' => '19','name' => 'El Tigre','city_id' => '47267','created_at' => NULL,'updated_at' => NULL],
            ['id' => '20','name' => 'Edmundo Barrios','city_id' => '47267','created_at' => NULL,'updated_at' => NULL],
            ['id' => '21','name' => 'Miguel Otero Silva','city_id' => '47267','created_at' => NULL,'updated_at' => NULL],
            ['id' => '22','name' => 'Puerto La Cruz','city_id' => '47268','created_at' => NULL,'updated_at' => NULL],
            ['id' => '23','name' => 'Pozuelos','city_id' => '47268','created_at' => NULL,'updated_at' => NULL],
            ['id' => '24','name' => 'San José de Guanipa','city_id' => '47269','created_at' => NULL,'updated_at' => NULL],
            ['id' => '25','name' => 'Guasdualito','city_id' => '47270','created_at' => NULL,'updated_at' => NULL],
            ['id' => '26','name' => 'Aramendi','city_id' => '47270','created_at' => NULL,'updated_at' => NULL],
            ['id' => '27','name' => 'El Amparo','city_id' => '47270','created_at' => NULL,'updated_at' => NULL],
            ['id' => '28','name' => 'San Camilo','city_id' => '47270','created_at' => NULL,'updated_at' => NULL],
            ['id' => '29','name' => 'Urdaneta','city_id' => '47270','created_at' => NULL,'updated_at' => NULL],
            ['id' => '30','name' => 'San Fernando','city_id' => '47271','created_at' => NULL,'updated_at' => NULL],
            ['id' => '31','name' => 'El Recreo','city_id' => '47271','created_at' => NULL,'updated_at' => NULL],
            ['id' => '32','name' => 'Peñalver','city_id' => '47271','created_at' => NULL,'updated_at' => NULL],
            ['id' => '33','name' => 'San Rafael de Atamaica','city_id' => '47271','created_at' => NULL,'updated_at' => NULL],
            ['id' => '34','name' => 'Andrés Eloy Blanco','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '35','name' => 'Choroní','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '36','name' => 'Francisco Linares Alcántara','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '37','name' => 'Girardot','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '38','name' => 'José Ángel Lamas','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '39','name' => 'José Félix Ribas','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '40','name' => 'José Rafael Revenga','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '41','name' => 'Libertador','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '42','name' => 'Mario Briceño Iragorry','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '43','name' => 'Ocumare de la Costa','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '44','name' => 'San Casimiro','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '45','name' => 'San Sebastián','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '46','name' => 'Santiago Mariño','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '47','name' => 'Santos Michelena','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '48','name' => 'Sucre','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '49','name' => 'Tovar','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '50','name' => 'Urdaneta','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '51','name' => 'Zamora','city_id' => '47276','created_at' => NULL,'updated_at' => NULL],
            ['id' => '52','name' => 'Barinas','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '53','name' => 'Alberto Arvelo Torrealba','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '54','name' => 'Alto Barinas','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '55','name' => 'Antonio José de Sucre','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '56','name' => 'Barinas (Catedral)','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '57','name' => 'Corazón de Jesús','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '58','name' => 'Dominga Ortiz de Páez','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '59','name' => 'El Carmen','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '60','name' => 'Juan Antonio Rodríguez Domínguez','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '61','name' => 'Romulo Betancourt','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '62','name' => 'San Silvestre','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '63','name' => 'Santa Inés','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '64','name' => 'Santa Lucía','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '65','name' => 'Torunos','city_id' => '47281','created_at' => NULL,'updated_at' => NULL],
            ['id' => '66','name' => 'Barinitas','city_id' => '47282','created_at' => NULL,'updated_at' => NULL],
            ['id' => '67','name' => 'Altamira de Cáceres','city_id' => '47282','created_at' => NULL,'updated_at' => NULL],
            ['id' => '68','name' => 'Calderas','city_id' => '47282','created_at' => NULL,'updated_at' => NULL],
            ['id' => '69','name' => 'Ciudad Bolívar','city_id' => '47283','created_at' => NULL,'updated_at' => NULL],
            ['id' => '70','name' => 'Agua Salada','city_id' => '47283','created_at' => NULL,'updated_at' => NULL],
            ['id' => '71','name' => 'Catedral','city_id' => '47283','created_at' => NULL,'updated_at' => NULL],
            ['id' => '72','name' => 'José Antonio Páez','city_id' => '47283','created_at' => NULL,'updated_at' => NULL],
            ['id' => '73','name' => 'La Sabanita','city_id' => '47283','created_at' => NULL,'updated_at' => NULL],
            ['id' => '74','name' => 'Marhuanta','city_id' => '47283','created_at' => NULL,'updated_at' => NULL],
            ['id' => '75','name' => 'Orinoco','city_id' => '47283','created_at' => NULL,'updated_at' => NULL],
            ['id' => '76','name' => 'Panapana','city_id' => '47283','created_at' => NULL,'updated_at' => NULL],
            ['id' => '77','name' => 'Vista Hermosa','city_id' => '47283','created_at' => NULL,'updated_at' => NULL],
            ['id' => '78','name' => 'Ciudad Guayana','city_id' => '47284','created_at' => NULL,'updated_at' => NULL],
            ['id' => '79','name' => 'Cachamay','city_id' => '47284','created_at' => NULL,'updated_at' => NULL],
            ['id' => '80','name' => 'Chirica','city_id' => '47284','created_at' => NULL,'updated_at' => NULL],
            ['id' => '81','name' => 'Dalla Costa','city_id' => '47284','created_at' => NULL,'updated_at' => NULL],
            ['id' => '82','name' => 'Once de Abril','city_id' => '47284','created_at' => NULL,'updated_at' => NULL],
            ['id' => '83','name' => 'Simón Bolívar','city_id' => '47284','created_at' => NULL,'updated_at' => NULL],
            ['id' => '84','name' => 'Unare','city_id' => '47284','created_at' => NULL,'updated_at' => NULL],
            ['id' => '85','name' => 'Universidad','city_id' => '47284','created_at' => NULL,'updated_at' => NULL],
            ['id' => '86','name' => 'Vista al Sol','city_id' => '47284','created_at' => NULL,'updated_at' => NULL],
            ['id' => '87','name' => 'Upata','city_id' => '47285','created_at' => NULL,'updated_at' => NULL],
            ['id' => '88','name' => 'Andrés Eloy Blanco','city_id' => '47285','created_at' => NULL,'updated_at' => NULL],
            ['id' => '89','name' => 'Pedro Cova','city_id' => '47285','created_at' => NULL,'updated_at' => NULL],
            ['id' => '90','name' => 'Goaigoaza','city_id' => '47286','created_at' => NULL,'updated_at' => NULL],
            ['id' => '91','name' => 'Guacara','city_id' => '47287','created_at' => NULL,'updated_at' => NULL],
            ['id' => '92','name' => 'Ciudad Alianza','city_id' => '47287','created_at' => NULL,'updated_at' => NULL],
            ['id' => '93','name' => 'Yagua','city_id' => '47287','created_at' => NULL,'updated_at' => NULL],
            ['id' => '94','name' => 'Guigue','city_id' => '47288','created_at' => NULL,'updated_at' => NULL],
            ['id' => '95','name' => 'Belén','city_id' => '47288','created_at' => NULL,'updated_at' => NULL],
            ['id' => '96','name' => 'Mariara','city_id' => '47289','created_at' => NULL,'updated_at' => NULL],
            ['id' => '97','name' => 'Aguas Calientes','city_id' => '47289','created_at' => NULL,'updated_at' => NULL],
            ['id' => '98','name' => 'Morón','city_id' => '47290','created_at' => NULL,'updated_at' => NULL],
            ['id' => '99','name' => 'Urama','city_id' => '47290','created_at' => NULL,'updated_at' => NULL],
            ['id' => '100','name' => 'Puerto Cabello','city_id' => '47291','created_at' => NULL,'updated_at' => NULL],
            ['id' => '101','name' => 'Borburata','city_id' => '47291','created_at' => NULL,'updated_at' => NULL],
            ['id' => '102','name' => 'Patanemo','city_id' => '47291','created_at' => NULL,'updated_at' => NULL],
            ['id' => '103','name' => 'San Joaquín','city_id' => '47292','created_at' => NULL,'updated_at' => NULL],
            ['id' => '104','name' => 'Tacarigua','city_id' => '47293','created_at' => NULL,'updated_at' => NULL],
            ['id' => '105','name' => 'Candelaria','city_id' => '47294','created_at' => NULL,'updated_at' => NULL],
            ['id' => '106','name' => 'Catedral','city_id' => '47294','created_at' => NULL,'updated_at' => NULL],
            ['id' => '107','name' => 'El Socorro','city_id' => '47294','created_at' => NULL,'updated_at' => NULL],
            ['id' => '108','name' => 'Miguel Peña','city_id' => '47294','created_at' => NULL,'updated_at' => NULL],
            ['id' => '109','name' => 'Negro Primero','city_id' => '47294','created_at' => NULL,'updated_at' => NULL],
            ['id' => '110','name' => 'Rafael Urdaneta','city_id' => '47294','created_at' => NULL,'updated_at' => NULL],
            ['id' => '111','name' => 'San Blas','city_id' => '47294','created_at' => NULL,'updated_at' => NULL],
            ['id' => '112','name' => 'San José','city_id' => '47294','created_at' => NULL,'updated_at' => NULL],
            ['id' => '113','name' => 'Santa Rosa','city_id' => '47294','created_at' => NULL,'updated_at' => NULL],
            ['id' => '114','name' => 'San Carlos','city_id' => '47295','created_at' => NULL,'updated_at' => NULL],
            ['id' => '115','name' => 'Juan de Mata Vivas','city_id' => '47295','created_at' => NULL,'updated_at' => NULL],
            ['id' => '116','name' => 'Tinaquillo','city_id' => '47296','created_at' => NULL,'updated_at' => NULL],
            ['id' => '117','name' => 'La Aguadita','city_id' => '47296','created_at' => NULL,'updated_at' => NULL],
            ['id' => '118','name' => 'Coro','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '119','name' => 'Antonio Díaz','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '120','name' => 'Cacique Manaure','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '121','name' => 'Colina','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '122','name' => 'Francisco Fajardo','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '123','name' => 'Guzmán Guillermo','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '124','name' => 'Monseñor Iturriza','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '125','name' => 'San Gabriel','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '126','name' => 'San José','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '127','name' => 'San Luis','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '128','name' => 'San Pedro','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '129','name' => 'Santa Ana','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '130','name' => 'Sucre','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '131','name' => 'Unión','city_id' => '47297','created_at' => NULL,'updated_at' => NULL],
            ['id' => '132','name' => 'Punta Cardón','city_id' => '47298','created_at' => NULL,'updated_at' => NULL],
            ['id' => '133','name' => 'Adícora','city_id' => '47298','created_at' => NULL,'updated_at' => NULL],
            ['id' => '134','name' => 'Baraived','city_id' => '47298','created_at' => NULL,'updated_at' => NULL],
            ['id' => '135','name' => 'Buena Vista','city_id' => '47298','created_at' => NULL,'updated_at' => NULL],
            ['id' => '136','name' => 'Jadacaquiva','city_id' => '47298','created_at' => NULL,'updated_at' => NULL],
            ['id' => '137','name' => 'Los Taques','city_id' => '47298','created_at' => NULL,'updated_at' => NULL],
            ['id' => '138','name' => 'Pueblo Nuevo','city_id' => '47298','created_at' => NULL,'updated_at' => NULL],
            ['id' => '139','name' => 'San Juan','city_id' => '47298','created_at' => NULL,'updated_at' => NULL],
            ['id' => '140','name' => 'Santa Cruz de Los Taques','city_id' => '47298','created_at' => NULL,'updated_at' => NULL],
            ['id' => '141','name' => 'Tacuato','city_id' => '47298','created_at' => NULL,'updated_at' => NULL],
            ['id' => '142','name' => 'Punto Fijo','city_id' => '47299','created_at' => NULL,'updated_at' => NULL],
            ['id' => '143','name' => 'Carirubana','city_id' => '47299','created_at' => NULL,'updated_at' => NULL],
            ['id' => '144','name' => 'Judibana','city_id' => '47299','created_at' => NULL,'updated_at' => NULL],
            ['id' => '145','name' => 'Norte','city_id' => '47299','created_at' => NULL,'updated_at' => NULL],
            ['id' => '146','name' => 'Sur','city_id' => '47299','created_at' => NULL,'updated_at' => NULL],
            ['id' => '147','name' => 'Altagracia de Orituco','city_id' => '47300','created_at' => NULL,'updated_at' => NULL],
            ['id' => '148','name' => 'Lezama','city_id' => '47300','created_at' => NULL,'updated_at' => NULL],
            ['id' => '149','name' => 'Ortiz','city_id' => '47300','created_at' => NULL,'updated_at' => NULL],
            ['id' => '150','name' => 'San Francisco de Macaira','city_id' => '47300','created_at' => NULL,'updated_at' => NULL],
            ['id' => '151','name' => 'San Rafael de Laya','city_id' => '47300','created_at' => NULL,'updated_at' => NULL],
            ['id' => '152','name' => 'Calabozo','city_id' => '47301','created_at' => NULL,'updated_at' => NULL],
            ['id' => '153','name' => 'El Calvario','city_id' => '47301','created_at' => NULL,'updated_at' => NULL],
            ['id' => '154','name' => 'El Rastro','city_id' => '47301','created_at' => NULL,'updated_at' => NULL],
            ['id' => '155','name' => 'Guardatinajas','city_id' => '47301','created_at' => NULL,'updated_at' => NULL],
            ['id' => '156','name' => 'San Juan de los Morros','city_id' => '47302','created_at' => NULL,'updated_at' => NULL],
            ['id' => '157','name' => 'Cantagallo','city_id' => '47302','created_at' => NULL,'updated_at' => NULL],
            ['id' => '158','name' => 'Parapara','city_id' => '47302','created_at' => NULL,'updated_at' => NULL],
            ['id' => '159','name' => 'Valle de la Pascua','city_id' => '47303','created_at' => NULL,'updated_at' => NULL],
            ['id' => '160','name' => 'Espino','city_id' => '47303','created_at' => NULL,'updated_at' => NULL],
            ['id' => '161','name' => 'Zaraza','city_id' => '47304','created_at' => NULL,'updated_at' => NULL],
            ['id' => '162','name' => 'San José de Unare','city_id' => '47304','created_at' => NULL,'updated_at' => NULL],
            ['id' => '163','name' => 'Barquisimeto','city_id' => '47305','created_at' => NULL,'updated_at' => NULL],
            ['id' => '164','name' => 'Aguedo Felipe Alvarado','city_id' => '47305','created_at' => NULL,'updated_at' => NULL],
            ['id' => '165','name' => 'Buena Vista','city_id' => '47305','created_at' => NULL,'updated_at' => NULL],
            ['id' => '166','name' => 'Catedral','city_id' => '47305','created_at' => NULL,'updated_at' => NULL],
            ['id' => '167','name' => 'Concepción','city_id' => '47305','created_at' => NULL,'updated_at' => NULL],
            ['id' => '168','name' => 'El Cují','city_id' => '47305','created_at' => NULL,'updated_at' => NULL],
            ['id' => '169','name' => 'Juan de Villegas','city_id' => '47305','created_at' => NULL,'updated_at' => NULL],
            ['id' => '170','name' => 'Juárez','city_id' => '47305','created_at' => NULL,'updated_at' => NULL],
            ['id' => '171','name' => 'La Unión','city_id' => '47305','created_at' => NULL,'updated_at' => NULL],
            ['id' => '172','name' => 'Tamaca','city_id' => '47305','created_at' => NULL,'updated_at' => NULL],
            ['id' => '173','name' => 'Unión','city_id' => '47305','created_at' => NULL,'updated_at' => NULL],
            ['id' => '174','name' => 'Cabudare','city_id' => '47306','created_at' => NULL,'updated_at' => NULL],
            ['id' => '175','name' => 'José Gregorio Bastidas','city_id' => '47306','created_at' => NULL,'updated_at' => NULL],
            ['id' => '176','name' => 'Carora','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '177','name' => 'Antonio Díaz','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '178','name' => 'Camacaro','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '179','name' => 'Castañeda','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '180','name' => 'Cecilio Zubillaga','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '181','name' => 'Chiquinquirá','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '182','name' => 'El Blanco','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '183','name' => 'Espinoza de los Monteros','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '184','name' => 'Heriberto Arroyo','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '185','name' => 'Lara','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '186','name' => 'Las Mercedes','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '187','name' => 'Manuel Morillo','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '188','name' => 'Montaña Verde','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '189','name' => 'Montes de Oca','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '190','name' => 'Torres','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '191','name' => 'Trinidad Samuel','city_id' => '47307','created_at' => NULL,'updated_at' => NULL],
            ['id' => '192','name' => 'El Tocuyo','city_id' => '47308','created_at' => NULL,'updated_at' => NULL],
            ['id' => '193','name' => 'La Miel','city_id' => '47308','created_at' => NULL,'updated_at' => NULL],
            ['id' => '194','name' => 'San Miguel','city_id' => '47308','created_at' => NULL,'updated_at' => NULL],
            ['id' => '195','name' => 'Santa Ana','city_id' => '47308','created_at' => NULL,'updated_at' => NULL],
            ['id' => '196','name' => 'Los Rastrojos','city_id' => '47309','created_at' => NULL,'updated_at' => NULL],
            ['id' => '197','name' => 'Manuel Antonio Díaz','city_id' => '47309','created_at' => NULL,'updated_at' => NULL],
            ['id' => '198','name' => 'Quibor','city_id' => '47310','created_at' => NULL,'updated_at' => NULL],
            ['id' => '199','name' => 'Cubiro','city_id' => '47310','created_at' => NULL,'updated_at' => NULL],
            ['id' => '200','name' => 'Cují','city_id' => '47310','created_at' => NULL,'updated_at' => NULL],
            ['id' => '201','name' => 'Duaca','city_id' => '47310','created_at' => NULL,'updated_at' => NULL],
            ['id' => '202','name' => 'Guarico','city_id' => '47310','created_at' => NULL,'updated_at' => NULL],
            ['id' => '203','name' => 'La Miel','city_id' => '47310','created_at' => NULL,'updated_at' => NULL],
            ['id' => '204','name' => 'San Miguel','city_id' => '47310','created_at' => NULL,'updated_at' => NULL],
            ['id' => '205','name' => 'Tintorero','city_id' => '47310','created_at' => NULL,'updated_at' => NULL],
            ['id' => '206','name' => 'Ejido','city_id' => '47311','created_at' => NULL,'updated_at' => NULL],
            ['id' => '207','name' => 'Acequias','city_id' => '47311','created_at' => NULL,'updated_at' => NULL],
            ['id' => '208','name' => 'Jají','city_id' => '47311','created_at' => NULL,'updated_at' => NULL],
            ['id' => '209','name' => 'La Mesa','city_id' => '47311','created_at' => NULL,'updated_at' => NULL],
            ['id' => '210','name' => 'San José','city_id' => '47311','created_at' => NULL,'updated_at' => NULL],
            ['id' => '211','name' => 'El Vigía','city_id' => '47312','created_at' => NULL,'updated_at' => NULL],
            ['id' => '212','name' => 'La Punta','city_id' => '47312','created_at' => NULL,'updated_at' => NULL],
            ['id' => '213','name' => 'Santa Elena de Arenales','city_id' => '47312','created_at' => NULL,'updated_at' => NULL],
            ['id' => '214','name' => 'Mérida','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '215','name' => 'Arias','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '216','name' => 'Caracciolo Parra Pérez','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '217','name' => 'Domingo Peña','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '218','name' => 'El Llano','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '219','name' => 'Gonzalo Picón Febres','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '220','name' => 'Jacinto Plaza','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '221','name' => 'Juan Rodríguez Suárez','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '222','name' => 'Lasso de la Vega','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '223','name' => 'Mariano Picón Salas','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '224','name' => 'Milla','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '225','name' => 'Osuna Rodríguez','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '226','name' => 'Sagrario','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '227','name' => 'El Morro','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '228','name' => 'Los Nevados','city_id' => '47313','created_at' => NULL,'updated_at' => NULL],
            ['id' => '229','name' => 'Baruta','city_id' => '47314','created_at' => NULL,'updated_at' => NULL],
            ['id' => '230','name' => 'El Cafetal','city_id' => '47314','created_at' => NULL,'updated_at' => NULL],
            ['id' => '231','name' => 'Las Minas de Baruta','city_id' => '47314','created_at' => NULL,'updated_at' => NULL],
            ['id' => '232','name' => 'Carrizal','city_id' => '47315','created_at' => NULL,'updated_at' => NULL],
            ['id' => '233','name' => 'Catia La Mar','city_id' => '47316','created_at' => NULL,'updated_at' => NULL],
            ['id' => '234','name' => 'Caucagüita','city_id' => '47317','created_at' => NULL,'updated_at' => NULL],
            ['id' => '235','name' => 'Chacao','city_id' => '47318','created_at' => NULL,'updated_at' => NULL],
            ['id' => '236','name' => 'Charallave','city_id' => '47319','created_at' => NULL,'updated_at' => NULL],
            ['id' => '237','name' => 'Las Brisas','city_id' => '47319','created_at' => NULL,'updated_at' => NULL],
            ['id' => '238','name' => 'Cúa','city_id' => '47320','created_at' => NULL,'updated_at' => NULL],
            ['id' => '239','name' => 'Nueva Cúa','city_id' => '47320','created_at' => NULL,'updated_at' => NULL],
            ['id' => '240','name' => 'El Cafetal','city_id' => '47321','created_at' => NULL,'updated_at' => NULL],
            ['id' => '241','name' => 'El Hatillo','city_id' => '47322','created_at' => NULL,'updated_at' => NULL],
            ['id' => '242','name' => 'La Lagunita','city_id' => '47322','created_at' => NULL,'updated_at' => NULL],
            ['id' => '243','name' => 'Filas de Mariche','city_id' => '47323','created_at' => NULL,'updated_at' => NULL],
            ['id' => '244','name' => 'Guarenas','city_id' => '47324','created_at' => NULL,'updated_at' => NULL],
            ['id' => '245','name' => 'Guatire','city_id' => '47325','created_at' => NULL,'updated_at' => NULL],
            ['id' => '246','name' => 'Bolívar','city_id' => '47325','created_at' => NULL,'updated_at' => NULL],
            ['id' => '247','name' => 'La Dolorita','city_id' => '47326','created_at' => NULL,'updated_at' => NULL],
            ['id' => '248','name' => 'Los Dos Caminos','city_id' => '47327','created_at' => NULL,'updated_at' => NULL],
            ['id' => '249','name' => 'Los Teques','city_id' => '47328','created_at' => NULL,'updated_at' => NULL],
            ['id' => '250','name' => 'Altagracia de la Montaña','city_id' => '47328','created_at' => NULL,'updated_at' => NULL],
            ['id' => '251','name' => 'Cecilio Acosta','city_id' => '47328','created_at' => NULL,'updated_at' => NULL],
            ['id' => '252','name' => 'El Jarillo','city_id' => '47328','created_at' => NULL,'updated_at' => NULL],
            ['id' => '253','name' => 'Paracotos','city_id' => '47328','created_at' => NULL,'updated_at' => NULL],
            ['id' => '254','name' => 'San Pedro','city_id' => '47328','created_at' => NULL,'updated_at' => NULL],
            ['id' => '255','name' => 'Tácata','city_id' => '47328','created_at' => NULL,'updated_at' => NULL],
            ['id' => '256','name' => 'Ocumare del Tuy','city_id' => '47329','created_at' => NULL,'updated_at' => NULL],
            ['id' => '257','name' => 'La Democracia','city_id' => '47329','created_at' => NULL,'updated_at' => NULL],
            ['id' => '258','name' => 'Petare','city_id' => '47330','created_at' => NULL,'updated_at' => NULL],
            ['id' => '259','name' => 'Caucagüita','city_id' => '47330','created_at' => NULL,'updated_at' => NULL],
            ['id' => '260','name' => 'Filas de Mariche','city_id' => '47330','created_at' => NULL,'updated_at' => NULL],
            ['id' => '261','name' => 'La Dolorita','city_id' => '47330','created_at' => NULL,'updated_at' => NULL],
            ['id' => '262','name' => 'Leoncio Martínez','city_id' => '47330','created_at' => NULL,'updated_at' => NULL],
            ['id' => '263','name' => 'Mariche','city_id' => '47330','created_at' => NULL,'updated_at' => NULL],
            ['id' => '264','name' => 'San Antonio de los Altos','city_id' => '47331','created_at' => NULL,'updated_at' => NULL],
            ['id' => '265','name' => 'Santa Teresa','city_id' => '47332','created_at' => NULL,'updated_at' => NULL],
            ['id' => '266','name' => 'El Cartanal','city_id' => '47332','created_at' => NULL,'updated_at' => NULL],
            ['id' => '267','name' => 'Maturín','city_id' => '47333','created_at' => NULL,'updated_at' => NULL],
            ['id' => '268','name' => 'Alto de los Godos','city_id' => '47333','created_at' => NULL,'updated_at' => NULL],
            ['id' => '269','name' => 'Boquerón','city_id' => '47333','created_at' => NULL,'updated_at' => NULL],
            ['id' => '270','name' => 'Jusepín','city_id' => '47333','created_at' => NULL,'updated_at' => NULL],
            ['id' => '271','name' => 'Las Cocuizas','city_id' => '47333','created_at' => NULL,'updated_at' => NULL],
            ['id' => '272','name' => 'La Pica','city_id' => '47333','created_at' => NULL,'updated_at' => NULL],
            ['id' => '273','name' => 'San Simón','city_id' => '47333','created_at' => NULL,'updated_at' => NULL],
            ['id' => '274','name' => 'Santa Cruz','city_id' => '47333','created_at' => NULL,'updated_at' => NULL],
            ['id' => '275','name' => 'Acarigua','city_id' => '47334','created_at' => NULL,'updated_at' => NULL],
            ['id' => '276','name' => 'Payara','city_id' => '47334','created_at' => NULL,'updated_at' => NULL],
            ['id' => '277','name' => 'Pimpinela','city_id' => '47334','created_at' => NULL,'updated_at' => NULL],
            ['id' => '278','name' => 'Araure','city_id' => '47335','created_at' => NULL,'updated_at' => NULL],
            ['id' => '279','name' => 'Río Acarigua','city_id' => '47335','created_at' => NULL,'updated_at' => NULL],
            ['id' => '280','name' => 'Guanare','city_id' => '47336','created_at' => NULL,'updated_at' => NULL],
            ['id' => '281','name' => 'Córdoba','city_id' => '47336','created_at' => NULL,'updated_at' => NULL],
            ['id' => '282','name' => 'Guanarito','city_id' => '47336','created_at' => NULL,'updated_at' => NULL],
            ['id' => '283','name' => 'San José de la Montaña','city_id' => '47336','created_at' => NULL,'updated_at' => NULL],
            ['id' => '284','name' => 'Virgen de la Coromoto','city_id' => '47336','created_at' => NULL,'updated_at' => NULL],
            ['id' => '285','name' => 'Villa Bruzual','city_id' => '47337','created_at' => NULL,'updated_at' => NULL],
            ['id' => '286','name' => 'Canelones','city_id' => '47337','created_at' => NULL,'updated_at' => NULL],
            ['id' => '287','name' => 'Santa Cruz','city_id' => '47337','created_at' => NULL,'updated_at' => NULL],
            ['id' => '288','name' => 'Carúpano','city_id' => '47338','created_at' => NULL,'updated_at' => NULL],
            ['id' => '289','name' => 'Santa Catalina','city_id' => '47338','created_at' => NULL,'updated_at' => NULL],
            ['id' => '290','name' => 'Santa Rosa','city_id' => '47338','created_at' => NULL,'updated_at' => NULL],
            ['id' => '291','name' => 'Santa Teresa','city_id' => '47338','created_at' => NULL,'updated_at' => NULL],
            ['id' => '292','name' => 'Bolívar','city_id' => '47338','created_at' => NULL,'updated_at' => NULL],
            ['id' => '293','name' => 'Macarapana','city_id' => '47338','created_at' => NULL,'updated_at' => NULL],
            ['id' => '294','name' => 'Yaguaraparo','city_id' => '47338','created_at' => NULL,'updated_at' => NULL],
            ['id' => '295','name' => 'Cumaná','city_id' => '47339','created_at' => NULL,'updated_at' => NULL],
            ['id' => '296','name' => 'Altagracia','city_id' => '47339','created_at' => NULL,'updated_at' => NULL],
            ['id' => '297','name' => 'Ayacucho','city_id' => '47339','created_at' => NULL,'updated_at' => NULL],
            ['id' => '298','name' => 'San Juan','city_id' => '47339','created_at' => NULL,'updated_at' => NULL],
            ['id' => '299','name' => 'Raúl Leoni','city_id' => '47339','created_at' => NULL,'updated_at' => NULL],
            ['id' => '300','name' => 'Santa Inés','city_id' => '47339','created_at' => NULL,'updated_at' => NULL],
            ['id' => '301','name' => 'Valentín Valiente','city_id' => '47339','created_at' => NULL,'updated_at' => NULL],
            ['id' => '302','name' => 'Gran Mariscal','city_id' => '47339','created_at' => NULL,'updated_at' => NULL],
            ['id' => '303','name' => 'La Fría','city_id' => '47340','created_at' => NULL,'updated_at' => NULL],
            ['id' => '304','name' => 'Boca de Grita','city_id' => '47340','created_at' => NULL,'updated_at' => NULL],
            ['id' => '305','name' => 'José Antonio Páez','city_id' => '47340','created_at' => NULL,'updated_at' => NULL],
            ['id' => '306','name' => 'San Cristóbal','city_id' => '47343','created_at' => NULL,'updated_at' => NULL],
            ['id' => '307','name' => 'Dr. Francisco Romero Lobo','city_id' => '47343','created_at' => NULL,'updated_at' => NULL],
            ['id' => '308','name' => 'La Concordia','city_id' => '47343','created_at' => NULL,'updated_at' => NULL],
            ['id' => '309','name' => 'Pedro María Morantes','city_id' => '47343','created_at' => NULL,'updated_at' => NULL],
            ['id' => '310','name' => 'San Juan Bautista','city_id' => '47343','created_at' => NULL,'updated_at' => NULL],
            ['id' => '311','name' => 'San Sebastián','city_id' => '47343','created_at' => NULL,'updated_at' => NULL],
            ['id' => '312','name' => 'San Juan de Colón','city_id' => '47344','created_at' => NULL,'updated_at' => NULL],
            ['id' => '313','name' => 'Hernández','city_id' => '47344','created_at' => NULL,'updated_at' => NULL],
            ['id' => '314','name' => 'Rojas','city_id' => '47344','created_at' => NULL,'updated_at' => NULL],
            ['id' => '315','name' => 'Táriba','city_id' => '47345','created_at' => NULL,'updated_at' => NULL],
            ['id' => '316','name' => 'Amenodoro Rangel Lamús','city_id' => '47345','created_at' => NULL,'updated_at' => NULL],
            ['id' => '317','name' => 'La Florida','city_id' => '47345','created_at' => NULL,'updated_at' => NULL],
            ['id' => '318','name' => 'Palo Gordo','city_id' => '47345','created_at' => NULL,'updated_at' => NULL],
            ['id' => '319','name' => 'Rubio','city_id' => '47372','created_at' => NULL,'updated_at' => NULL],
            ['id' => '320','name' => 'Bramón','city_id' => '47372','created_at' => NULL,'updated_at' => NULL],
            ['id' => '321','name' => 'La Palmita','city_id' => '47372','created_at' => NULL,'updated_at' => NULL],
            ['id' => '322','name' => 'Quinimarí','city_id' => '47372','created_at' => NULL,'updated_at' => NULL],
            ['id' => '323','name' => 'Trujillo','city_id' => '47346','created_at' => NULL,'updated_at' => NULL],
            ['id' => '324','name' => 'Andrés Linares','city_id' => '47346','created_at' => NULL,'updated_at' => NULL],
            ['id' => '325','name' => 'Chiquinquirá','city_id' => '47346','created_at' => NULL,'updated_at' => NULL],
            ['id' => '326','name' => 'Cristóbal Mendoza','city_id' => '47346','created_at' => NULL,'updated_at' => NULL],
            ['id' => '327','name' => 'La Paz','city_id' => '47346','created_at' => NULL,'updated_at' => NULL],
            ['id' => '328','name' => 'Matriz','city_id' => '47346','created_at' => NULL,'updated_at' => NULL],
            ['id' => '329','name' => 'Monseñor Carrillo','city_id' => '47346','created_at' => NULL,'updated_at' => NULL],
            ['id' => '330','name' => 'Valera','city_id' => '47347','created_at' => NULL,'updated_at' => NULL],
            ['id' => '331','name' => 'Juan Ignacio Montilla','city_id' => '47347','created_at' => NULL,'updated_at' => NULL],
            ['id' => '332','name' => 'La Beatriz','city_id' => '47347','created_at' => NULL,'updated_at' => NULL],
            ['id' => '333','name' => 'La Puerta','city_id' => '47347','created_at' => NULL,'updated_at' => NULL],
            ['id' => '334','name' => 'Mendoza','city_id' => '47347','created_at' => NULL,'updated_at' => NULL],
            ['id' => '335','name' => 'Mercedes Díaz','city_id' => '47347','created_at' => NULL,'updated_at' => NULL],
            ['id' => '336','name' => 'San Luis','city_id' => '47347','created_at' => NULL,'updated_at' => NULL],
            ['id' => '337','name' => 'La Guaira','city_id' => '47349','created_at' => NULL,'updated_at' => NULL],
            ['id' => '338','name' => 'Caraballeda','city_id' => '47349','created_at' => NULL,'updated_at' => NULL],
            ['id' => '339','name' => 'Carayaca','city_id' => '47349','created_at' => NULL,'updated_at' => NULL],
            ['id' => '340','name' => 'Carlos Soublette','city_id' => '47349','created_at' => NULL,'updated_at' => NULL],
            ['id' => '341','name' => 'Caruao','city_id' => '47349','created_at' => NULL,'updated_at' => NULL],
            ['id' => '342','name' => 'Macuto','city_id' => '47349','created_at' => NULL,'updated_at' => NULL],
            ['id' => '343','name' => 'Maiquetía','city_id' => '47349','created_at' => NULL,'updated_at' => NULL],
            ['id' => '344','name' => 'Naiguatá','city_id' => '47349','created_at' => NULL,'updated_at' => NULL],
            ['id' => '345','name' => 'Urimare','city_id' => '47349','created_at' => NULL,'updated_at' => NULL],
            ['id' => '346','name' => 'El Junko','city_id' => '47349','created_at' => NULL,'updated_at' => NULL],
            ['id' => '347','name' => 'San Felipe','city_id' => '47353','created_at' => NULL,'updated_at' => NULL],
            ['id' => '348','name' => 'Albarico','city_id' => '47353','created_at' => NULL,'updated_at' => NULL],
            ['id' => '349','name' => 'San Javier','city_id' => '47353','created_at' => NULL,'updated_at' => NULL],
            ['id' => '350','name' => 'Yaritagua','city_id' => '47354','created_at' => NULL,'updated_at' => NULL],
            ['id' => '351','name' => 'San Andrés','city_id' => '47354','created_at' => NULL,'updated_at' => NULL],
            ['id' => '352','name' => 'Nirgua','city_id' => '47352','created_at' => NULL,'updated_at' => NULL],
            ['id' => '353','name' => 'Salom','city_id' => '47352','created_at' => NULL,'updated_at' => NULL],
            ['id' => '354','name' => 'Chivacoa','city_id' => '47351','created_at' => NULL,'updated_at' => NULL],
            ['id' => '355','name' => 'Campo Elías','city_id' => '47351','created_at' => NULL,'updated_at' => NULL],
            ['id' => '356','name' => 'Cocorote','city_id' => '47351','created_at' => NULL,'updated_at' => NULL],
            ['id' => '357','name' => 'Maracaibo','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '358','name' => 'Antonio Borjas Romero','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '359','name' => 'Bolívar','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '360','name' => 'Cacique Mara','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '361','name' => 'Caracciolo Parra Pérez','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '362','name' => 'Cecilio Acosta','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '363','name' => 'Cristo de Aranza','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '364','name' => 'Coquivacoa','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '365','name' => 'Chiquinquirá','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '366','name' => 'Francisco Eugenio Bustamante','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '367','name' => 'Idelfonso Vásquez','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '368','name' => 'Juana de Ávila','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '369','name' => 'Luis Hurtado Higuera','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '370','name' => 'Manuel Dagnino','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '371','name' => 'Mariano Parra León','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '372','name' => 'Olegario Villalobos','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '373','name' => 'Raúl Leoni','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '374','name' => 'Santa Lucía','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '375','name' => 'Venancio Pulgar','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '376','name' => 'San Isidro','city_id' => '47360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '377','name' => 'Caracas','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '378','name' => '23 de Enero','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '379','name' => 'Altagracia','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '380','name' => 'Antímano','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '381','name' => 'Candelaria','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '382','name' => 'Caricuao','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '383','name' => 'Catedral','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '384','name' => 'Coche','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '385','name' => 'El Junquito','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '386','name' => 'El Paraíso','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '387','name' => 'El Recreo','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '388','name' => 'El Valle','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '389','name' => 'La Pastora','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '390','name' => 'La Vega','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '391','name' => 'Macarao','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '392','name' => 'San Agustín','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '393','name' => 'San Bernardino','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '394','name' => 'San José','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '395','name' => 'San Juan','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '396','name' => 'San Pedro','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '397','name' => 'Santa Rosalía','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '398','name' => 'Santa Teresa','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '399','name' => 'Sucre','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '400','name' => 'La Candelaria','city_id' => '48357','created_at' => NULL,'updated_at' => NULL],
            ['id' => '401','name' => 'La Asunción','city_id' => '48358','created_at' => NULL,'updated_at' => NULL],
            ['id' => '402','name' => 'Arismendi','city_id' => '48358','created_at' => NULL,'updated_at' => NULL],
            ['id' => '403','name' => 'Porlamar','city_id' => '48359','created_at' => NULL,'updated_at' => NULL],
            ['id' => '404','name' => 'Mariño','city_id' => '48359','created_at' => NULL,'updated_at' => NULL],
            ['id' => '405','name' => 'Pampatar','city_id' => '48360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '406','name' => 'Maneiro','city_id' => '48360','created_at' => NULL,'updated_at' => NULL],
            ['id' => '407','name' => 'Juan Griego','city_id' => '48361','created_at' => NULL,'updated_at' => NULL],
            ['id' => '408','name' => 'Gómez','city_id' => '48361','created_at' => NULL,'updated_at' => NULL],
            ['id' => '409','name' => 'Marcano','city_id' => '48361','created_at' => NULL,'updated_at' => NULL],
            ['id' => '410','name' => 'San Juan Bautista','city_id' => '48362','created_at' => NULL,'updated_at' => NULL],
            ['id' => '411','name' => 'Díaz','city_id' => '48362','created_at' => NULL,'updated_at' => NULL],
            ['id' => '412','name' => 'El Valle del Espíritu Santo','city_id' => '48363','created_at' => NULL,'updated_at' => NULL],
            ['id' => '413','name' => 'García','city_id' => '48363','created_at' => NULL,'updated_at' => NULL],
            ['id' => '414','name' => 'Santa Ana','city_id' => '48364','created_at' => NULL,'updated_at' => NULL],
            ['id' => '415','name' => 'Paraguachí','city_id' => '48365','created_at' => NULL,'updated_at' => NULL],
            ['id' => '416','name' => 'Antolín del Campo','city_id' => '48365','created_at' => NULL,'updated_at' => NULL],
            ['id' => '417','name' => 'Punta de Piedras','city_id' => '48366','created_at' => NULL,'updated_at' => NULL],
            ['id' => '418','name' => 'Tubores','city_id' => '48366','created_at' => NULL,'updated_at' => NULL],
            ['id' => '419','name' => 'Boca de Río','city_id' => '48367','created_at' => NULL,'updated_at' => NULL],
            ['id' => '420','name' => 'Península de Macanao','city_id' => '48367','created_at' => NULL,'updated_at' => NULL],
            ['id' => '421','name' => 'Villalba','city_id' => '48372','created_at' => NULL,'updated_at' => NULL],
            ['id' => '422','name' => 'Tucupita','city_id' => '48368','created_at' => NULL,'updated_at' => NULL],
            ['id' => '423','name' => 'Sierra Imataca','city_id' => '48369','created_at' => NULL,'updated_at' => NULL],
            ['id' => '424','name' => 'Imataca','city_id' => '48369','created_at' => NULL,'updated_at' => NULL],
            ['id' => '425','name' => 'Cinco de Julio','city_id' => '48369','created_at' => NULL,'updated_at' => NULL],
            ['id' => '426','name' => 'Juan Bautista Arismendi','city_id' => '48369','created_at' => NULL,'updated_at' => NULL],
            ['id' => '427','name' => 'Manuel Piar','city_id' => '48369','created_at' => NULL,'updated_at' => NULL],
            ['id' => '428','name' => 'Rómulo Gallegos','city_id' => '48369','created_at' => NULL,'updated_at' => NULL],
            ['id' => '429','name' => 'Pedernales','city_id' => '48370','created_at' => NULL,'updated_at' => NULL],
            ['id' => '430','name' => 'Luis Beltrán Prieto Figueroa','city_id' => '48370','created_at' => NULL,'updated_at' => NULL],
            ['id' => '431','name' => 'Curiapo','city_id' => '48371','created_at' => NULL,'updated_at' => NULL],
            ['id' => '432','name' => 'Almirante Luis Brión','city_id' => '48371','created_at' => NULL,'updated_at' => NULL],
            ['id' => '433','name' => 'Francisco Aniceto Lugo','city_id' => '48371','created_at' => NULL,'updated_at' => NULL],
            ['id' => '434','name' => 'Manuel Renaud','city_id' => '48371','created_at' => NULL,'updated_at' => NULL],
            ['id' => '435','name' => 'Padre Barral','city_id' => '48371','created_at' => NULL,'updated_at' => NULL],
            ['id' => '436','name' => 'Santos de Abelgas','city_id' => '48371','created_at' => NULL,'updated_at' => NULL],        ];

        foreach ($parishes as $parish) {
            // Verificar que la ciudad existe antes de crear la parroquia (búsqueda por ID)
            $cityExists = City::where('id', $parish['city_id'])->exists();
            if ($cityExists) {
                // Usar firstOrCreate para evitar duplicados si se ejecuta múltiples veces
                Parroquia::firstOrCreate(
                    ['id' => $parish['id']], // Buscar por ID específico
                    [
                        'name' => $parish['name'],
                        'city_id' => $parish['city_id'], // Mantener búsqueda por ID
                        'created_at' => $parish['created_at'],
                        'updated_at' => $parish['updated_at'],
                    ]
                );
            }
        }
    }
}
